FROM node:18.15.0 AS build

WORKDIR /app

COPY . .

RUN npm install --force

RUN npm run build

FROM node:18.15.0

WORKDIR /app

COPY --from=build /app/dist/inserisci-commesse/ /app

EXPOSE 4200

CMD ["npm", "start"]